# With these PostgreSQL settings
db.url=jdbc:postgresql://postgresdb:5432/todo_app
db.username=postgres
db.password=postgres
db.driver=org.postgresql.Driver

# Split.io Configuration
split.api.key=6sau7u97ujp98svua4bmb3jqcsn20arpqlod